### ISSUE TITLE
app-crypt/keybase-bin x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by sysfu** [powerman/powerman-overlay#14]
Just upgrade to version app-crypt/keybase-bin-6.2.3_p20231016183016 and now unable to send any messages. This is the error message I get

![keybase-msg-send-error](https://github.com/powerman/powerman-overlay/assets/829699/d35aa8da-18d8-4e76-9b90-9abb3922b494)

Similar Keybase [issue from 2016](https://github.com/keybase/keybase-issues/issues/2371)

Update: looks like it's [system wide](https://github.com/keybase/keybase-issues/issues/4225)

**Comment by sysfu** [comment]
Looks like a version bump is the only fix

https://github.com/keybase/keybase-issues/issues/4225#issuecomment-1874375182

**Comment by sysfu** [comment]
Reddit thread https://www.reddit.com/r/Keybase/comments/18vbqhu/messages_cant_be_sent_because_the_ssl_cert_expired/

**Comment by powerman** [comment]
Fixed by 25ad2d2.
