### ISSUE TITLE
service-x should depend on service-dbus as its run file does depend on it

### ISSUE THREAD

**Issue by fusion809** [powerman/powerman-overlay#6]
Hi,

I noticed that the service-x run file includes a line that starts the dbus service so shouldn't it depend on it?

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I read the ebuild but oddly for me I emerged service-x but service-dbus didn't get drawn in.

**Comment by powerman** [comment]
I think you right, but I'm busy at the moment, will fix this later.

**Comment by powerman** [comment]
Well, this is strange. To me ebuild looks good, all dependencies are in place: https://github.com/powerman/powerman-overlay/blob/master/runit-service/service-x/service-x-2.1.0.ebuild#L18

I've also checked dependencies on some server (which doesn't have Xorg/dbus installed at all) and everything looks fine:
```
# emerge -pv service-x | grep service-
[ebuild  N    ~] runit-service/service-dbus-2.0.0::powerman  1 KiB
[ebuild  N    ~] runit-service/service-consolekit-2.0.0::powerman  1 KiB
[ebuild  N    ~] runit-service/service-x-2.1.0::powerman  1 KiB

The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
# required by sys-auth/consolekit-1.2.0::gentoo
# required by runit-service/service-consolekit-2.0.0::powerman
# required by runit-service/service-x-2.1.0::powerman
# required by service-x (argument)
>=dev-libs/glib-2.50.3-r1 dbus
```
Please reopen this if you find out how it happens to skip this dependency on your system and I'll have something to fix.
