### ISSUE TITLE
lurch / libomemo: 12-byte IVs patch

### ISSUE THREAD

**Issue by Neustradamus** [powerman/powerman-overlay#7]
Hello @powerman and @hartwork (Sping),

Here:
- https://github.com/powerman/powerman-overlay/search?q=gkdr
- https://github.com/gentoo-mirror/powerman/search?q=gkdr
- https://packages.gentoo.org/packages/x11-plugins/lurch

Can you add the 12-byte IVs patch?
- https://github.com/gkdr/libomemo/pull/27

Explanation:
- https://github.com/gkdr/libomemo/issues/24

In the same time, can you update axc, carbons and lurch too?
- https://github.com/gkdr/axc/releases
- https://github.com/gkdr/carbons/releases
- https://github.com/gkdr/lurch/releases

Thanks in advance.

**Comment by powerman** [comment]
Fixed in 815b753.

**Comment by Neustradamus** [comment]
@powerman: Thanks! :)

**Comment by hartwork** [comment]
@powerman as you know there is lurch in core Gentoo by now and it does have [an upgraded libomemo](https://github.com/gentoo/gentoo/commit/6ba43559b8ffd133fd9ce598e832de9335d1169f) now .  Would you mind dropping lurch from the powerman overlay? Thank you!

**Comment by powerman** [comment]
@hartwork Removed. Thanks!

**Comment by hartwork** [comment]
Thank you!

**Comment by Neustradamus** [comment]
@powerman, @hartwork: Thanks for "harmonization".
